;;; emacs-solo-icons.el --- File type icon definitions for Emacs Solo  -*- lexical-binding: t; -*-
;;
;; Author: Rahul Martim Juliato
;; URL: https://github.com/LionyxML/emacs-solo
;; Package-Requires: ((emacs "30.1"))
;; Keywords: faces, convenience
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:
;;
;; Defines file type icon mappings (emoji and nerd-font variants)
;; used by other Emacs Solo features (Dired, eshell, ibuffer).

;;; Code:

(defvar emacs-solo/file-icons
  '(("el"        :nerd "" :emoji "📜")
    ("rb"        :nerd "" :emoji "💎")
    ("js"        :nerd "" :emoji "⚙️")
    ("ts"        :nerd "" :emoji "⚙️")
    ("json"      :nerd "" :emoji "🗂️")
    ("md"        :nerd "" :emoji "📝")
    ("txt"       :nerd "" :emoji "📝")
    ("html"      :nerd "" :emoji "🌐")
    ("css"       :nerd "" :emoji "🎨")
    ("scss"      :nerd "" :emoji "🎨")
    ("png"       :nerd "" :emoji "🖼️")
    ("jpg"       :nerd "" :emoji "🖼️")
    ("jpeg"      :nerd "" :emoji "🖼️")
    ("gif"       :nerd "" :emoji "🖼️")
    ("svg"       :nerd "" :emoji "🖼️")
    ("pdf"       :nerd "" :emoji "📄")
    ("zip"       :nerd "" :emoji "📦")
    ("tar"       :nerd "" :emoji "📦")
    ("gz"        :nerd "" :emoji "📦")
    ("bz2"       :nerd "" :emoji "📦")
    ("7z"        :nerd "" :emoji "📦")
    ("org"       :nerd "" :emoji "🦄")
    ("sh"        :nerd "" :emoji "💻")
    ("c"         :nerd "" :emoji "🅲")
    ("h"         :nerd "" :emoji "📘")
    ("cpp"       :nerd "" :emoji "🅲")
    ("hpp"       :nerd "" :emoji "📘")
    ("py"        :nerd "" :emoji "🐍")
    ("java"      :nerd "" :emoji "☕")
    ("go"        :nerd "" :emoji "🌍")
    ("rs"        :nerd "" :emoji "💨")
    ("php"       :nerd "" :emoji "🐘")
    ("pl"        :nerd "" :emoji "🐍")
    ("lua"       :nerd "" :emoji "🎮")
    ("ps1"       :nerd "" :emoji "🔧")
    ("exe"       :nerd "" :emoji "⚡")
    ("dll"       :nerd "" :emoji "🔌")
    ("bat"       :nerd "" :emoji "⚡")
    ("yaml"      :nerd "" :emoji "⚙️")
    ("toml"      :nerd "" :emoji "⚙️")
    ("ini"       :nerd "" :emoji "⚙️")
    ("csv"       :nerd "" :emoji "📊")
    ("xls"       :nerd "" :emoji "📊")
    ("xlsx"      :nerd "" :emoji "📊")
    ("sql"       :nerd "" :emoji "🗄️")
    ("log"       :nerd "" :emoji "📝")
    ("apk"       :nerd "" :emoji "📱")
    ("dmg"       :nerd "" :emoji "💻")
    ("iso"       :nerd "" :emoji "💿")
    ("torrent"   :nerd "" :emoji "🧲")
    ("bak"       :nerd "" :emoji "🗃️")
    ("tmp"       :nerd "" :emoji "⚠️")
    ("desktop"   :nerd "" :emoji "🖥️")
    ("md5"       :nerd "" :emoji "🔐")
    ("sha256"    :nerd "" :emoji "🔐")
    ("pem"       :nerd "" :emoji "🔐")
    ("sqlite"    :nerd "" :emoji "🗄️")
    ("db"        :nerd "" :emoji "🗄️")
    ("gpg"       :nerd "" :emoji "🔐")
    ("hash"      :nerd "" :emoji "#️⃣")
    ("mp3"       :nerd "" :emoji "🎶")
    ("wav"       :nerd "" :emoji "🎶")
    ("flac"      :nerd "" :emoji "🎶")
    ("mail"      :nerd "" :emoji "📧")
    ("ogg"       :nerd "" :emoji "🎶")
    ("m4a"       :nerd "" :emoji "🎶")
    ("mp4"       :nerd "" :emoji "🎬")
    ("avi"       :nerd "" :emoji "🎬")
    ("mov"       :nerd "" :emoji "🎬")
    ("mkv"       :nerd "" :emoji "🎬")
    ("webm"      :nerd "" :emoji "🎬")
    ("flv"       :nerd "" :emoji "🎬")
    ("ico"       :nerd "" :emoji "🖼️")
    ("ttf"       :nerd "" :emoji "🔠")
    ("otf"       :nerd "" :emoji "🔠")
    ("eot"       :nerd "" :emoji "🔠")
    ("woff"      :nerd "" :emoji "🔠")
    ("woff2"     :nerd "" :emoji "🔠")
    ("epub"      :nerd "" :emoji "📚")
    ("mobi"      :nerd "" :emoji "📚")
    ("azw3"      :nerd "" :emoji "📚")
    ("fb2"       :nerd "" :emoji "📚")
    ("chm"       :nerd "" :emoji "📚")
    ("tex"       :nerd "" :emoji "📚")
    ("bib"       :nerd "" :emoji "📚")
    ("rar"       :nerd "" :emoji "📦")
    ("xz"        :nerd "" :emoji "📦")
    ("zst"       :nerd "" :emoji "📦")
    ("tar.xz"    :nerd "" :emoji "📦")
    ("tar.zst"   :nerd "" :emoji "📦")
    ("tar.gz"    :nerd "" :emoji "📦")
    ("tgz"       :nerd "" :emoji "📦")
    ("mpg"       :nerd "" :emoji "🎬")
    ("webp"      :nerd "" :emoji "🖼️")
    ("3gp"       :nerd "" :emoji "🎬")
    ("ogv"       :nerd "" :emoji "🎬")
    ("srt"       :nerd "" :emoji "🔠")
    ("vtt"       :nerd "" :emoji "🔠")
    ("cue"       :nerd "" :emoji "📀")
    ("terminal"  :nerd "" :emoji "💻")
    ("info"      :nerd "ℹ" :emoji "ℹ️")
    ("direddir"  :nerd "" :emoji "📁")
    ("diredfile" :nerd "" :emoji "📄")
    ("wranch"    :nerd "" :emoji "🔧")
    ("news"      :nerd "" :emoji "📰"))
  "Icons for specific file extensions, keyed by style.")

(defun emacs-solo/file-icon (name)
  "Look up icon for file extension NAME in `emacs-solo/file-icons'."
  (let* ((row (assoc name emacs-solo/file-icons))
         (style (cond
                 ((memq 'nerd emacs-solo-icon-modules) :nerd)
                 ((string= (getenv "TERM") "xterm-kitty") :noicons)
                 (t :emoji)))
         (val (plist-get (cdr row) style)))
    (if (and val (char-displayable-p (string-to-char val)))
        val "")))

(provide 'emacs-solo-icons)
;;; emacs-solo-icons.el ends here
